name: galletas_app_nueva
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Dependencias de la App ---
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  
  # --- Base de Datos ---
  sqflite: ^2.3.3+1

  # --- Funcionalidades Principales ---
  barcode_widget: ^2.0.4
  mobile_scanner: ^7.0.1
  csv: ^6.0.0
  share_plus: ^11.0.0
  intl: ^0.19.0 # AÃ±adido: Necesario para formatear fechas y horas.

  # --- Permisos y Acceso a Hardware ---
  permission_handler: ^12.0.1
  gal: ^2.2.0
  path_provider: ^2.1.3
  device_info_plus: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
